### ISSUE TITLE
Add changelog in future release

### ISSUE THREAD

**Issue by szlin** [yuriescl/runoverssh#1]
I am going to package your utility into Debian archive. Please consider that add CHANGELOG in future release, thus it makes easier for users and contributors to see precisely what notable changes have been made between each release of the utility.
Thanks.

**Comment by yuriescl** [comment]
Thank you!
Yes, I will include it in the next release.

**Comment by yuriescl** [comment]
CHANGELOG added, along with a few other improvements. To update the Debian package to the newest version, do I have to create a bug in the mailing list?

**Comment by imZack** [comment]
@yuriescl it's landed! https://packages.debian.org/source/sid/runoverssh
No, you don't have to create any issues in the mailing list. Just notify package's maintainer.

**Comment by yuriescl** [comment]
Thank you! Really appreciate the support :)

**Comment by szlin** [comment]
@yuriescl  Thanks for your contribution. I will sponsor new package :) 

Please feel free to discuss with us if you have any questions
