### ISSUE TITLE
How to specify the port no ?

### ISSUE THREAD

**Issue by ravinayag** [yuriescl/runoverssh#9]
hi,  How to specify the port no ?

**Comment by yuriescl** [comment]
@ravinayag Hi, you mean the SSH port? This can be set using the `--sshflags` option. For example, to connect to port 50000 instead of the default 22, you can use:
```
runoverssh --sshflags '-p 50000' user command host
```
The above overrides the default ssh flags. To use the default ssh flags you have to add them to your `--sshflags` option

**Comment by yuriescl** [comment]
I'll consider this closed since there's no more feedback.
